import * as XLSX from 'xlsx';
import PptxGenJS from 'pptxgenjs';
import officeParser from 'officeparser';

const escapeCsvCell = (value: string) => `"${value.replace(/"/g, '""')}"`;

export const createWorkbookFromText = (input: { text: string; title?: string }) => {
  const lines = input.text
    .split(/\r?\n/)
    .map((line) => line.trim())
    .filter(Boolean)
    .slice(0, 80);

  const title = (input.title || 'Astro Sheet').trim();
  const rows: string[][] = [
    ['Title', title],
    ['Generated', new Date().toISOString()],
    [],
    ['Section', 'Details'],
    ...(lines.length > 0
      ? lines.map((line, index) => [`Item ${index + 1}`, line])
      : [['Summary', input.text.trim() || 'No content']]),
  ];

  const sheet = XLSX.utils.aoa_to_sheet(rows);
  const workbook = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(workbook, sheet, 'Atlas');
  return XLSX.write(workbook, { type: 'buffer', bookType: 'xlsx' }) as Buffer;
};

export const createPresentationFromText = async (input: {
  title: string;
  text: string;
  slideCount?: number;
}) => {
  const totalSlides = Math.min(15, Math.max(2, Number(input.slideCount || 6)));
  const contentSlides = totalSlides - 1;
  const pptx = new PptxGenJS();
  pptx.layout = 'LAYOUT_WIDE';

  const toDataUri = (buffer: Buffer, mime: string) =>
    `data:${mime};base64,${buffer.toString('base64')}`;

  const loadBackgroundImage = async (seed: string) => {
    try {
      const res = await fetch(`https://picsum.photos/seed/${encodeURIComponent(seed)}/1600/900`, {
        cache: 'no-store',
      });
      if (!res.ok) return null;
      const mime = res.headers.get('content-type') || 'image/jpeg';
      const arrayBuffer = await res.arrayBuffer();
      return toDataUri(Buffer.from(arrayBuffer), mime);
    } catch {
      return null;
    }
  };

  const titleImage = await loadBackgroundImage(`${input.title}-hero`);
  const titleSlide = pptx.addSlide();
  titleSlide.background = { color: '0B1220' };
  if (titleImage) {
    titleSlide.addImage({ data: titleImage, x: 0, y: 0, w: 13.33, h: 7.5 });
    titleSlide.addShape(pptx.ShapeType.rect, {
      x: 0,
      y: 0,
      w: 13.33,
      h: 7.5,
      fill: { color: '0B1220', transparency: 38 },
      line: { color: '0B1220', transparency: 100 },
    });
  }
  titleSlide.addText(input.title || 'Atlas Presentation', {
    x: 0.7,
    y: 0.9,
    w: 11.6,
    h: 1.2,
    fontSize: 40,
    bold: true,
    color: 'F8FAFC',
  });
  titleSlide.addText('Generated by Atlas', {
    x: 0.75,
    y: 2.15,
    w: 4.5,
    h: 0.4,
    fontSize: 12,
    color: 'D1D5DB',
  });

  const bullets = input.text
    .split(/\r?\n/)
    .map((line) => line.replace(/^[-*]\s*/, '').trim())
    .filter((line) => Boolean(line) && !/^#{1,6}\s*/.test(line));

  const chunks: string[][] = [];
  const chunkSize = Math.max(2, Math.ceil(Math.max(bullets.length, contentSlides * 2) / contentSlides));
  for (let i = 0; i < bullets.length; i += chunkSize) {
    chunks.push(bullets.slice(i, i + chunkSize));
  }
  if (chunks.length === 0) {
    chunks.push([input.text.trim() || 'No content provided']);
  }

  while (chunks.length < contentSlides) {
    chunks.push(['Key insight', 'Supporting detail']);
  }

  const palette = ['0F172A', '111827', '1E1B4B', '0C4A6E', '292524'];
  const imageCache = await Promise.all(
    Array.from({ length: contentSlides }).map((_, idx) =>
      loadBackgroundImage(`${input.title}-slide-${idx + 1}`),
    ),
  );

  chunks.slice(0, contentSlides).forEach((chunk, idx) => {
    const slide = pptx.addSlide();
    slide.background = { color: palette[idx % palette.length] };
    const image = imageCache[idx];
    if (image) {
      slide.addImage({ data: image, x: 8.2, y: 0, w: 5.13, h: 7.5 });
      slide.addShape(pptx.ShapeType.rect, {
        x: 8.2,
        y: 0,
        w: 5.13,
        h: 7.5,
        fill: { color: '000000', transparency: 28 },
        line: { color: '000000', transparency: 100 },
      });
    }
    slide.addText(`Slide ${idx + 2}`, {
      x: 0.7,
      y: 0.45,
      w: 6.9,
      h: 0.6,
      fontSize: 20,
      bold: true,
      color: 'E5E7EB',
    });
    slide.addText(
      chunk.map((item) => ({ text: item, options: { bullet: { indent: 18 } } })),
      {
        x: 0.75,
        y: 1.2,
        w: 6.95,
        h: 5.7,
        fontSize: 17,
        color: 'F8FAFC',
        breakLine: true,
      },
    );
  });

  const buffer = (await pptx.write({ outputType: 'nodebuffer' })) as Buffer;
  return buffer;
};

export const extractWorkbookText = (buffer: Buffer) => {
  const workbook = XLSX.read(buffer, { type: 'buffer' });
  const lines: string[] = [];
  workbook.SheetNames.slice(0, 5).forEach((sheetName) => {
    const sheet = workbook.Sheets[sheetName];
    if (!sheet) return;
    const rows = XLSX.utils.sheet_to_json<(string | number | boolean | null)[]>(sheet, {
      header: 1,
      blankrows: false,
      raw: false,
    });
    lines.push(`# ${sheetName}`);
    rows.slice(0, 200).forEach((row) => {
      const serialized = (row || [])
        .map((cell) => (cell == null ? '' : String(cell)))
        .join(' | ')
        .trim();
      if (serialized) lines.push(serialized);
    });
  });
  return lines.join('\n');
};

export const extractOfficeText = async (buffer: Buffer) => {
  const text = await officeParser.parseOfficeAsync(buffer);
  return String(text || '').trim();
};

export const toCsvFromText = (text: string) =>
  ['Section,Details', `${escapeCsvCell('Summary')},${escapeCsvCell(text.replace(/\r?\n/g, ' '))}`].join('\n');
